---
title: "Use cases of veriNA3d"
author:
  - name: Diego Gallego Perez
    affiliation:
    - University of Barcelona - Dept. Biochemistry and Molecular Biomedicine
    - Institute for Research in Biomedicine - (IRB Barcelona), Barcelona 
        Institute of Science and Technology
date: "`r Sys.Date()`"
output: BiocStyle::pdf_document
bibliography: references.bib
vignette: >
  %\VignetteIndexEntry{}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(
    collapse   = TRUE,
    comment    = "#>",
    message    = FALSE,
    warning    = FALSE,
    fig.width  = 6,
    fig.height = 2,
    fig.wide   = TRUE
)

```
# Introduction

The R language provides an excellent interface for statistical analysis, which
is also interesting from the point of view of structural data. This gap was 
filled in 2006 by the R package 
[bio3d](http://thegrantlab.org/bio3d/) [@Grant2006]. 
It was presented as a 
suite of tools to handle PDB formated structures, and trajectories. 
It integrates a variety of functions to analyse these data, from 
sequence to 3D structure (RMSD, NMA, PCA... see their 
[documentation](http://thegrantlab.org/bio3d/html/index.html) for details), 
and later on a parser for mmCIF files also.

The R package presented in here, veriNA3d, does not replace bio3d at all.
Rather, it was developed on top of bio3d to cover additional necessities. 
The only common tool integrated in both packages is a parser for mmCIF files
(see below). veriNA3d is mainly intended (but not limited) to the analysis of 
Nucleic Acids. It integrates a higher level of abstraction than bio3d since it
also allows the analysis of datasets, in addition to analysis of single
structures. The functions in the package could be divided in the following 
blocks (complete list in README file):

* Dataset level: Functions to get and analyse lists of pdb IDs. This includes
the representative lists of RNA by [@Leontis2012] and analytical functions.

* Structure level: Functions to get data, parse mmCIF files and analyse these
data.

* Plots: Some examples of plots to be done after the previous analysis. 


# Parsing mmCIF files and the R S4 Object "CIF".

## Origin and standardization of mmCIF files

Atomic structural data of macromolecules has long been distributed in the PDB
file format. However, one of its main limitations is the column size for the 
coordinates data, which didn't allowed to save molecules with more than 99999
atoms, more than 62 chains or more than 9999 residues (in a chain).

Given that the Protein Data Bank is continously growing and accepting bigger
structures (e.g. a whole *E.coli* ribosome has over 140000 atoms - pdbID 4V4S),
an alternative file format became the standard: the mmCIF file format.

The mmCIFs are an evolution of the Crystallographic Information File (CIF), 
originally used for small molecule structures. It stands for 
**m**acro**m**olecular **CIF** file, and it has actually coexisted with the PDB
format since the 1997. However, since the PDB is easier to parse and such big
structures didn't populate the database at the time, most software has been
developed for the PDB format.

The PDB format was definetely frozen in 2014. However, it will still coexist
with the standard mmCIF format as long as "old" software evolves to accept
mmCIF.

## The CIF object

The R language supports different kinds of 
[objects](http://adv-r.had.co.nz/OO-essentials.html),
being the S3 and S4 the most common ones. The S3 objects 
Later on, i
also integrated a parser for mmCIF files.


# Main use case: Manage Nucleic Acid datasets

Get Leontis list, change representative structures and analyse them with one 
of the pipelines

# Use case: Querying the EMBL-EBI REST API

Query EBI API and how to construct new queries!

# Use case: eRMSD

For two NMR models of RNA/DNA, compute the eRMSD

# Use case: Generate substructures

For a given structure (CIF or PDB), generate a smaller PDB with the region of 
interest and surroundings


# References
