// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cifParserC
List cifParserC(std::string strings);
RcppExport SEXP _veriNA3d_cifParserC(SEXP stringsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type strings(stringsSEXP);
    rcpp_result_gen = Rcpp::wrap(cifParserC(strings));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_veriNA3d_cifParserC", (DL_FUNC) &_veriNA3d_cifParserC, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_veriNA3d(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
