// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hello
void hello();
RcppExport SEXP _veriNA3d_hello() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    hello();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_veriNA3d_hello", (DL_FUNC) &_veriNA3d_hello, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_veriNA3d(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
